# Generated by Django 2.0.2 on 2019-08-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=30)),
                ('PercentChange30', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PercentChange365', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PercentChange', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('WeekHigh52', models.DecimalField(decimal_places=2, max_digits=6)),
                ('WeekLow52', models.DecimalField(decimal_places=2, max_digits=6)),
                ('LastTradedPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('High', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Open', models.DecimalField(decimal_places=2, max_digits=6)),
                ('TradedValInCrs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('TradedVolInLacs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
